[window]
padding = { x = 10, y = 10 }
opacity = 0.8
blur = true

[font]
normal = { family = "Iosevka Curly", style = "Regular" }
size = 12

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" }
]

# Colors (Gruvbox Material Dark Medium)

[colors.primary]
background = '#1C1C1C'
foreground = '#dfbf8e'

[colors.normal]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e78a4e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e3a84e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'
